name : Email Sender
on:
  workflow_dispatch:

jobs:
    send_email:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.x'
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install smtplib email 
            - name: "Send email"
              run: |
                python script.py
              env:
                    WORKFLOW_NAME: ${{ github.workflow }}
                    REPO_NAME: ${{ github.repository }}
                    WORKFLOW_RUN_ID: ${{ github.run_id }}
                    SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
                    EMAIL_TO: ${{ secrets.SENDER_EMAIL }}
                    EMAIL_FROM: ${{ secrets.RECEIVER_EMAIL }}
                    